In [1]:
import pandas as pd
import altair as alt

In [2]:
alt.renderers.enable('default')

RendererRegistry.enable('default')

In [3]:
df = pd.read_csv("GLB.Ts_dSST.csv", header=1)

In [4]:
df

,Year,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,J-D,D-N,DJF,MAM,JJA,SON
0,1880,-0.29,-0.18,-0.11,-0.19,-0.11,-0.23,-0.21,-0.09,-0.16,-0.23,-0.20,-0.23,-0.19,***,***,-0.14,-0.18,-0.20
1,1881,-0.15,-0.17,0.04,0.04,0.02,-0.20,-0.06,-0.02,-0.13,-0.20,-0.21,-0.10,-0.10,-.11,-.18,0.03,-0.09,-0.18
2,1882,0.15,0.15,0.04,-0.18,-0.16,-0.26,-0.20,-0.05,-0.10,-0.24,-0.16,-0.24,-0.10,-.09,.06,-0.10,-0.17,-0.17
3,1883,-0.31,-0.39,-0.13,-0.17,-0.20,-0.12,-0.08,-0.15,-0.20,-0.14,-0.22,-0.16,-0.19,-.20,-.31,-0.16,-0.12,-0.19
4,1884,-0.15,-0.08,-0.37,-0.42,-0.36,-0.40,-0.34,-0.26,-0.27,-0.24,-0.30,-0.28,-0.29,-.28,-.13,-0.39,-0.34,-0.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,2013,0.66,0.55,0.66,0.52,0.57,0.65,0.57,0.65,0.76,0.67,0.78,0.65,0.64,.63,.58,0.58,0.63,0.74
134,2014,0.73,0.52,0.76,0.77,0.85,0.66,0.56,0.80,0.88,0.81,0.66,0.78,0.73,.72,.63,0.79,0.67,0.78
135,2015,0.81,0.87,0.90,0.74,0.75,0.79,0.71,0.79,0.81,1.07,1.02,1.10,0.86,.84,.82,0.80,0.76,0.97
136,2016,1.15,1.34,1.30,1.07,0.90,0.78,0.82,0.99,0.87,0.89,0.90,0.82,0.99,1.01,1.19,1.09,0.86,0.88
137,2017,0.96,1.11,1.13,0.93,0.88,0.70,0.81,0.86,0.74,0.88,0.87,0.89,0.90,.89,.96,0.98,0.79,0.83

In [5]:
df = pd.melt(df, id_vars=['Year'], value_vars=['J-D'])

In [6]:
df

     Year variable  value
0    1880      J-D  -0.19
1    1881      J-D  -0.10
2    1882      J-D  -0.10
3    1883      J-D  -0.19
4    1884      J-D  -0.29
..    ...      ...    ...
133  2013      J-D   0.64
134  2014      J-D   0.73
135  2015      J-D   0.86
136  2016      J-D   0.99
137  2017      J-D   0.90

[138 rows x 3 columns]

In [7]:
x_axis = [el for el in range(df['Year'].min(), df['Year'].max(), 10)]

In [8]:
plot = alt.Chart(
    df,
    title=['Annual Global Surface Temperature,', 'Relative to Late 19th Century Average']).mark_point().encode(
    alt.X(
        field='Year', 
        title=None,
        type='ordinal', 
        axis=alt.Axis(values=x_axis, grid=True, labelAngle=0)
        ),
    alt.Y(
        field='value', 
        title=None,
        type='quantitative', 
        axis=alt.Axis(labelExpr="(datum.value > 0 ? '+' + datum.value + '\u00b0' "
                      ": (datum.value == -0.6) ? null: datum.value + '\u00b0')", tickCount=10)
    )
)

In [9]:
axis_text = alt.Chart(pd.DataFrame([{'x': 2010, 'y': 0}])).mark_text(
    text=['HOTTER THAN THE', '1880-1899 AVERAGE', '', 'COLDER'],
    dy = -25
).encode(
    x='x:O',
    y='y:Q'
)

In [10]:
ox_axis = alt.Chart(pd.DataFrame({'y': [0]})).mark_rule().encode(y='y')

In [11]:
right_side_labels = alt.Chart(
    df,
    ).mark_text(dx=20).transform_filter(
    alt.FieldOneOfPredicate(field='Year', oneOf=[1944, 2014, 2015, 2017])
).encode(
    alt.X(
        field='Year', 
        title=None,
        type='ordinal', 
        axis=alt.Axis(values=x_axis, grid=True, labelAngle=0)
        ),
    alt.Y(
        field='value', 
        title=None,
        type='quantitative', 
        axis=alt.Axis(labelExpr="(datum.value > 0 ? '+' + datum.value + '\u00b0' "
                      ": (datum.value == -0.6) ? null: datum.value + '\u00b0')", tickCount=10)
    ),
    alt.Text('Year:O')
)

In [12]:
left_side_labels = alt.Chart(
    df,
    ).mark_text(dx=-20).transform_filter(
    alt.FieldOneOfPredicate(field='Year', oneOf=[1904, 1998])
).encode(
    alt.X(
        field='Year', 
        title=None,
        type='ordinal', 
        axis=alt.Axis(values=x_axis, grid=True, labelAngle=0)
        ),
    alt.Y(
        field='value', 
        title=None,
        type='quantitative', 
        axis=alt.Axis(labelExpr="(datum.value > 0 ? '+' + datum.value + '\u00b0' "
                      ": (datum.value == -0.6) ? null: datum.value + '\u00b0')", tickCount=10)
    ),
    alt.Text('Year:O')
)

In [13]:
bold_labels = alt.Chart(
    df,
    ).mark_text(dx=20, fontWeight="bold").transform_filter(
    alt.FieldOneOfPredicate(field='Year', oneOf=[2016])
).encode(
    alt.X(
        field='Year', 
        title=None,
        type='ordinal', 
        axis=alt.Axis(values=x_axis, grid=True, labelAngle=0)
        ),
    alt.Y(
        field='value', 
        title=None,
        type='quantitative', 
        axis=alt.Axis(labelExpr="(datum.value > 0 ? '+' + datum.value + '\u00b0' "
                      ": (datum.value == -0.6) ? null: datum.value + '\u00b0')", tickCount=10)
    ),
    alt.Text('Year:O')
)

In [14]:
alt.layer(plot, ox_axis, axis_text, right_side_labels, left_side_labels, bold_labels).properties(
        width=720, 
        height=400,
    ).configure_point(
        color='gray',
        fill='#E55B13',
        strokeWidth=0.8
    ).configure_title(
        anchor='start',
        dx = 50,
        dy = 50,
        fontWeight = 800
    ).configure_axis(
        labelColor='gray',
        ticks = False,
        domain=False,
    ).configure_view(
    strokeOpacity=0
    )

alt.LayerChart(...)